apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/homework"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    tier: interaction
  name: application
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    tier: interaction

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_HOST_AUTH_METHOD: "trust"
  POSTGRES_DB: "homework"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    tier: database
    app: postgres
  name: postgres
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    tier: database
    app: postgres

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  labels:
    tier: interaction
    app: application
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: interaction
  template:
    metadata:
      labels:
        tier: interaction
    spec:
      containers:
        - name: application
          image: shipim/homework:1.0.0
          envFrom:
            - configMapRef:
                name: application-config
          ports:
            - containerPort: 8080
              protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    tier: database
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: database
      app: postgres
  template:
    metadata:
      labels:
        tier: database
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          envFrom:
            - configMapRef:
                name: postgres-config
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP