server:
  port: 8080

spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/homework
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  graphql:
    graphiql:
      enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: homework
    redis:
      host: localhost
      port: 6379
      password: password
  cache:
    type: redis
    cache-names: redis-cache
    redis:
      time-to-live: 30000

minio:
  url: http://localhost:9000
  port: 9000
  accessKey: user
  secretKey: password
  secure: false
  bucket: minio-storage
  image-size: 10485760

jwt:
  secret:
    access:
      key: B6E5061FADAD40CCAEBDD0F4B3EB3DEE3F4FCE86695FA0076BA9E0A894A53140
      expiration: 300
    refresh:
      key: 6cc6e57d734e612ff0c4c24aec8eef175ef34befc6c52ca73e82ba695d2c69c4
      expiration: 600