apiVersion: v1
kind: Service
metadata:
  labels:
    tier: database
    app: postgres
  name: postgres
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    tier: database
    app: postgres