apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    tier: database
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: database
      app: postgres
  template:
    metadata:
      labels:
        tier: database
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          envFrom:
            - configMapRef:
                name: postgres-config
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP